### ISSUE TITLE
SYSLIB0021: Derived cryptographic types are obsolete

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#155]
Replace [System.Security.Cryptography.MD5CryptoServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.md5cryptoserviceprovider)
With [System.Security.Cryptography.MD5.create](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.MD5.create?view=net-7.0)

Warning: [SYSLIB0021](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0021)

Implementation: 
https://github.com/guibranco/CrispyWaffle/blob/abc21d40f0a5797559f1109310f23cc53957cde0/Src/CrispyWaffle/Cryptography/Security.cs#L111

**Comment by tiagoschaffer** [comment]
Hello.
Just replace and run the test is a viable solution?

**Comment by guibranco** [comment]
@tiagoschaffer yes, it is! 

Let me know if you are keen to work on this, I will assign it to you =D

**Comment by tiagoschaffer** [comment]
Yes I am
