### ISSUE TITLE
Add serializer for `System.Text.Json`

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#192]
This issue is about adding a new serializer adapter to the project.

The new serializer should use the [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-8-0) instead of the [Newtonsoft.Json](https://www.newtonsoft.com/json) used by [JsonSerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/JsonSerializerAdapter.cs).

Currently, we have the following serializers in the project: 
- [BinarySerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BinarySerializerAdapter.cs)
- [JsonSerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/JsonSerializerAdapter.cs)
- [XmlSerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/XmlSerializerAdapter.cs)

The proposed solution is to rename `JsonSerializerAdapter` to `NewtonsoftJsonSerializerAdapter` and also add the `JsonSerializerAdapter` that will implement the serialization and deserialization logic using the `System.Text.Json`.

The class should implement the [ISerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/ISerializerAdapter.cs) interface. More precisely, it should implement the [BaseSerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BaseSerializerAdapter.cs) abstract class.

**Comment by yekxp** [comment]
Hello, my name is Jakub and I am a student of Technical University in Kosice and software developer in Siemens Healthineers and I would be very happy if I could work on this issue. It would be the part of the course where we have to help a project on GitHub. Could you assign me to it, please?

**Comment by guibranco** [comment]
Hi @yekxp, of course, I assigned it for you, let me know if you need more context on it or if you need any details during your progress.

**Comment by guibranco** [comment]
@yekxp any progress on this? Do you need any help?

**Comment by Looseling** [comment]
Hi @guibranco, Could you tell a bit more about the ticket? thanks!

**Comment by guibranco** [comment]
Hi @Looseling, sure. 

First, thanks for your interest in helping out with this project.

This issue (I will update the issue description to reflect this comment) is about adding a new serializer adapter to the project.

The new serializer should use the [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-8-0) instead of the [Newtonsoft.Json](https://www.newtonsoft.com/json) used by [JsonSerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/JsonSerializerAdapter.cs).

Currently, we have the following serializers in the project: 
- [BinarySerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BinarySerializerAdapter.cs)
- [JsonSerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/JsonSerializerAdapter.cs)
- [XmlSerializerAdapter.cs](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/XmlSerializerAdapter.cs)

The proposed solution is to rename `JsonSerializerAdapter` to `NewtonsoftJsonSerializerAdapter` and also add the `JsonSerializerAdapter` that will implement the serialization and deserialization logic using the `System.Text.Json`.

The class should implement the [ISerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/ISerializerAdapter.cs) interface. More precisely, it should implement the [BaseSerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BaseSerializerAdapter.cs) abstract class.

**Comment by Looseling** [comment]
Sounds clear! Pls assign it to me

**Comment by guibranco** [comment]
Hi @Looseling, any progress on this one? 

Let me know if you need any help!

**Comment by Looseling** [comment]
Hi! 
Happy new year! 

I am fine 
in System.Text.Json not all features have a direct equivalent, so some adjustments are necessary. :D

**Comment by Looseling** [comment]
Hey,

I've tried to push changes on the branch but got:
remote: Permission to guibranco/CrispyWaffle.git denied to Looseling.
fatal: unable to access 'https://github.com/guibranco/CrispyWaffle.git/': The requested URL returned error: 403

is it on my side or am I lacking permission?

**Comment by guibranco** [comment]
You should fork this repository and work in your own fork; then, when it's done, you should submit a pull request from your fork/branch to mine. I will review it, and if everything is okay, I will merge it!
