### ISSUE TITLE
Extract `EventLog` and remove dependency `System.Diagnostics.EventLog` from `CrispyWaffle` project

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#202]
Extract the `System.Diagnostics.EventLog` from `Src/CrispyWaffle/Log/Providers` and `Src/CrispyWaffle/Log/Adapters` to a dedicated project `CrispyWaffle.EventLog` and remove the dependency of `System.Diagnostics.EventLog` in `CrispyWaffle` project.

**Files:**

- [EventLogAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Log/Adapters/EventLogAdapter.cs)
- [EventLogProvider](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Log/Providers/EventLogProvider.cs)
- [IEventIdProvider](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Log/Providers/IEventIdProvider.cs)
- [EventIdProvider](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Log/Providers/EventIdProvider.cs)

Steps to archive the goal:

- Create a new project in the CrispyWaffle solution named `CrispyWaffle.EventLog`
- Add a dependency to the main project in this newly created project
- Uninstall the [System.Diagnostics.EventLog](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/CrispyWaffle.csproj#L26) from the main project
- Install the `System.Diagnostics.EventLog` package in the new project
- If you are new to .NET, you can just `cut` the line from one project and paste it in the other, this will be enough to uninstall/install a nugget package
- Move the 4 files listed above in the main project to this newly created project
- Keep the same file structure for the moved files, so it will be something like `Src/CrispyWaffle.EventLog/Log/Adapters` (for the adapter) and `Src/CrispyWaffle.EventLog/Log/Providers` (for the other 3 files)

**Comment by Majdi-Zlitni** [comment]
Hello @guibranco could you please explain more what should be done in this issue, thanks

**Comment by guibranco** [comment]
Hi @Majdi-Zlitni , the goal here is to extract the dependencies of `System.Diagnostics.EventLog` to a separate project/package within this repository. 

So, we will have a `CrispyWaffle.EventLog` project and subsequentially NuGet package for the event log.
That is a simple task:

- Create a new project in the CrispyWaffle solution named `CrispyWaffle.EventLog`
- Add a dependency to the main project in this newly created project
- Uninstall the [System.Diagnostics.EventLog](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/CrispyWaffle.csproj#L26) from the main project
- Install the `System.Diagnostics.EventLog` package in the new project
- If you are new to .NET, you can just `cut` the line from one project and paste to the other, this will be enough to uninstall/install a nugget package
- Move the 4 files in the main project to this newly created project (the files are listed in the first comment of this issue)
- Keep the same file structure for the moved files, so it will be something like `Log/Adapters` (for the adapter) and `Log/Providers` (for the other 3 files)

**Comment by Majdi-Zlitni** [comment]
Okay, thanks for the explanation, could you assign me to this task.

**Comment by guibranco** [comment]
@Majdi-Zlitni any progress on this? Do you need any help?

**Comment by msant01s** [comment]
Is this task still open? I am new to this and would like to help.
