### ISSUE TITLE
Remove retry rules from FtpClient class.

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#211]
The retry rules (retry 3x, wait 1s between retries) should not reside in the code of this tool, instead it should be something that who is using the code decides how to deal with it and how to retry (manually or using Polly)

https://github.com/guibranco/CrispyWaffle/blob/5bd17e96223b3661bdfd25cbf0f9089d613fb84b/Src/CrispyWaffle.Utils/Communications/FtpClient.cs#L244

**Comment by Yousef-Majidi** [comment]
Do you just need the `Sleep` and the `if` condition that checks the `attempt` count removed from `FtpClient.cs`? 
So, in the case of a `WebException`, the code should simply throw a new `FtpClientException`? 

If my understanding is correct, I can take care of this.

**Comment by guibranco** [comment]
Yes, that's correct. I just want this to be a simple implementation, without any opinion on how to deal with possible errors.

If you find any more improvement on that class or in other, feel free to change it! I will appreciate it.

**Comment by Yousef-Majidi** [comment]
Will do. Thank you for the confirmation.
