### ISSUE TITLE
[FEATURE] Add Request/Response pattern in EventsDispatcher (maybe a CommandsDispatcher)

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#358]
### Description

Currently, we have the `EventsDispatcher` that receives an `IEvent` and dispatches it overall `EventsHandlers.`

The idea here is to have a `CommandsDispatcher` that will receive an `ICommand` as input, and dispatch/send it for one, and one only `CommandHandler` and send back to the caller the response.dispatch/send it for one and only one `CommandHandler`, and send the response back to the caller

### Tech notes

Use memory transport for this (maybe in the future we can have distributed system arch for this).

**Comment by thiagochfc** [comment]
Hi!

Could I take this one?

Posso precisar de ajuda a qualquer momento. Ok?

(Se podermos falar em português, para mim é mais fácil, :smile:)

**Comment by guibranco** [comment]
Yes, of course. Let me know what you need!

---

SIm, podemos falar sim, só escrevi em ingles para mais gente conseguir entender, mas sem problemas!

**Comment by guibranco** [comment]
O ideal seria seguir o padrão do `EventsDispatcher`, mas criar uma classe a parte `CommandsDispatcher`, assim tudo relativo a isso ficaria nessa classe.

**Comment by thiagochfc** [comment]
Perfeito, obrigado.
