### ISSUE TITLE
[FEATURE] Upgrade `ElasticSearch` dependencies

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#444]
### Description

Currently, the project uses both deprecated dependencies:

- [Elasticsearch.Net](https://www.nuget.org/packages/Elasticsearch.Net/)
- [Nest](https://www.nuget.org/packages/Nest)

We must replace it with the up-to-date version, which introduces breaking changes:

- [Elastic.Clients.Elasticsearch](https://www.nuget.org/packages/Elastic.Clients.Elasticsearch/)

### Tech notes

Some content to address the breaking changes:

- [Release notes v8.0.0](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html)

**Comment by Mohammad-Haris** [comment]
@guibranco, I would be happy to help on this one too.

**Comment by guibranco** [comment]
Cool, @Mohammad-Haris. I have assigned it to you!
