### ISSUE TITLE
[FEATURE] Remove binary serializer classes from codebase

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#462]
### Description

Remove the [BinarySerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BinarySerializerAdapter.cs) and all related code in the `CrispyWaffle.Serializers` namespace.

### Tech notes

`BinarySerializer` has security issues and was flagged as obsolete in .NET 7.0 and higher:

- [[Breaking change]: Legacy serialization infrastructure APIs marked obsolete](https://github.com/dotnet/docs/issues/34893)
- [Deserialization risks in use of BinaryFormatter and related types](https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)
- [BinaryFormatter serialization methods are obsolete and prohibited in ASP.NET apps](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/binaryformatter-serialization-obsolete?source=recommendations)

### Additional information

- [ ] Remove [BinarySerializerAdapter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/Adapters/BinarySerializerAdapter.cs) class/file.
- [ ] Remove the `Binary` item from [SerializationFormat](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/SerializerFormat.cs) enumeration.
- [ ] Remove usage/calls to `BinarySerializerAdapter` from the [SerializerFactory](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/SerializerFactory.cs) class.
- [ ] Remove usage/calls to `BinarySerializerAdapter` from the [SerializerConverter](https://github.com/guibranco/CrispyWaffle/blob/main/Src/CrispyWaffle/Serialization/SerializerConverter.cs) class.
- [ ] Remove references to the `Binary` format in the documentation [docs/user-guide/basic-usage](https://github.com/guibranco/CrispyWaffle/blob/main/docs/user-guide/basic-usage.md).
- [ ] Update the class diagram in the docs to reflect the current status of the project in file [docs/user-guide/basic-usage](https://github.com/guibranco/CrispyWaffle/blob/main/docs/user-guide/basic-usage.md).

**Comment by Mohammad-Haris** [comment]
Hey, I'll take this. Please assign.

**Comment by Mohammad-Haris** [comment]
Sure @guibranco. I have time today, will look into it.

**Comment by Mohammad-Haris** [comment]
Hey @guibranco, how is the class diagram edited?

**Comment by guibranco** [comment]
@Mohammad-Haris, just add it to the PR or in the issue, and I will update it. It is hosted in a custom service that generates the animation and allows us to zoom in/out.

**Comment by Mohammad-Haris** [comment]
:)
I spent almost an hour trying to figure out from the JS script and then the network calls from the docs page, but it was all just loading pngs. I'll create the PR.
