### ISSUE TITLE
[DOCS] Add `RollingTextFileLogAdapter` documentation

### ISSUE THREAD

**Issue by guibranco** [guibranco/CrispyWaffle#483]
### Description

Add docs about RollingTextFileLogAdapter, with some usage examples.

**Comment by Mohammad-Haris** [comment]
Hey @guibranco, I can take this. Any ideas on how the related PR could be improved?

**Comment by guibranco** [comment]
Hi @Mohammad-Haris, thanks!

We can add usage examples to it on the `/docs/` directory.

**Comment by Mohammad-Haris** [comment]
@guibranco I meant the previous PR, the closed one (#479). Any ideas for improvement on that one?

**Comment by guibranco** [comment]
I think we can use a normal .txt file instead of a .json (I do like the structured log file format, but it also breaks the standard for the other log adapters - we might have an optional parameter to set the log format to use the standard TXT or a JSON file or even XML files). Since we have serialization in the project, it would be a quick & easy implementation (just my thoughts, not a requirement).
